
const REQUEST_STATUS = {
  REQUEST_STATUS_OPEN: 1,
  REQUEST_STATUS_RECEIVED: 2,
  REQUEST_STATUS_FULFILLING: 3,
  REQUEST_STATUS_FULFILLED: 4,
  REQUEST_STATUS_CANCELLED: 5,
  REQUEST_STATUS_REJECTED: 6,
  REQUEST_STATUS_ERROR: 100,
}

module.exports = {
  REQUEST_STATUS,
}