# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod verify
builds:
  -
    id: "go-ooo"
    binary: go-ooo
    main: ./
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -X go-ooo/version.Version={{.Version}}
      - -X go-ooo/version.Commit={{.FullCommit}}
    flags:
      - -mod=readonly
      - -tags="netgo"
    hooks:
      pre: go mod verify

archives:
  -
    id: "go-ooo"
    builds:
      - go-ooo
    name_template: >-
      {{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{ end }}
    format: tar.gz

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^build:'
      - '^dist:'
